; ========== PRIHLÁSENIE Z LINPHONE ==========
; Username: kori
; Password: kori123
; Domain: 127.0.0.1:5061
; Registrar URI (Advanced): sip:127.0.0.1:5061
; Outbound Proxy (Advanced): sip:127.0.0.1:5061
; Transport: UDP
; ============================================

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5061

[kori]
type=endpoint
context=from-sip
aors=kori
auth=kori
disallow=all
allow=ulaw
allow=alaw
allow=opus
direct_media=no

[kori]
type=aor
max_contacts=1

[kori]
type=auth
auth_type=userpass
username=kori
password=kori123
